'use client';

import { useState, useRef, useCallback } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import {
  Search, Bell, Plus, Download, Save, Check,
  LayoutDashboard, Package, Layers, Factory,
  Image, BarChart3, BookTemplate, Menu, X,
  ChevronDown, Sparkles, Home, FileText,
  CheckCircle, AlertCircle, Info, Trash2,
  type LucideIcon,
} from 'lucide-react';
import { useAppStore } from '@/store/appStore';
import type { AppView } from '@/types';

const NAV_TABS: { id: string; label: string; icon: LucideIcon; view: AppView }[] = [
  { id: 'home',          label: 'Home',          icon: Home,            view: 'dashboard'   },
  { id: 'workspace',     label: 'Workspace',     icon: LayoutDashboard, view: 'workspace'   },
  { id: 'templates',     label: 'Templates',     icon: BookTemplate,    view: 'templates'   },
  { id: 'manufacturing', label: 'Manufacturing', icon: Factory,         view: 'manufacturing'},
  { id: 'inventory',     label: 'Inventory',     icon: Package,         view: 'inventory'   },
  { id: 'brand-assets',  label: 'Brand Assets',  icon: Image,           view: 'brand-assets'},
  { id: 'analytics',     label: 'Analytics',     icon: BarChart3,       view: 'analytics'   },
];

// ─────────────────────────────────────────────────────────────────────────────
// EXPORT HELPERS
// ─────────────────────────────────────────────────────────────────────────────
function exportAsPNG(item: { name: string; sku: string; type: string; color?: string }) {
  const canvas = document.createElement('canvas');
  canvas.width = 1200;
  canvas.height = 1600;
  const ctx = canvas.getContext('2d');
  if (!ctx) return;

  // Background
  ctx.fillStyle = '#F8FAFC';
  ctx.fillRect(0, 0, 1200, 1600);

  // Product area
  ctx.fillStyle = item.color || '#1E293B';
  ctx.beginPath();
  ctx.roundRect(100, 100, 1000, 1200, 24);
  ctx.fill();

  // Brand mark
  const textColor = isLightHex(item.color || '#1E293B') ? '#1E293B' : '#FFFFFF';
  ctx.fillStyle = textColor;
  ctx.globalAlpha = 0.15;
  ctx.beginPath();
  ctx.arc(600, 550, 80, 0, Math.PI * 2);
  ctx.fill();
  ctx.globalAlpha = 0.7;
  ctx.font = 'bold 48px Inter, system-ui, sans-serif';
  ctx.textAlign = 'center';
  ctx.fillText('BT', 600, 565);

  // Product name
  ctx.globalAlpha = 0.9;
  ctx.font = 'bold 36px Inter, system-ui, sans-serif';
  ctx.fillText(item.name.toUpperCase(), 600, 700);

  // SKU
  ctx.globalAlpha = 0.5;
  ctx.font = '24px Inter, system-ui, sans-serif';
  ctx.fillText(item.sku, 600, 750);
  ctx.globalAlpha = 1;

  // Footer
  ctx.fillStyle = '#64748B';
  ctx.font = '18px Inter, system-ui, sans-serif';
  ctx.fillText(`${item.type} · Boxtacks Studio`, 600, 1450);

  // Trigger download
  const link = document.createElement('a');
  link.download = `${item.name.replace(/\s+/g, '-').toLowerCase()}-export.png`;
  link.href = canvas.toDataURL('image/png');
  link.click();
}

function exportAsPDF(item: { name: string; sku: string; type: string; status: string; costing?: { unitCost: number; retailPrice: number; currency: string } }) {
  // Generate a printable spec sheet as HTML and open in a new window for print/PDF
  const costInfo = item.costing
    ? `<tr><td>Unit Cost</td><td>${item.costing.currency} ${item.costing.unitCost.toFixed(2)}</td></tr>
       <tr><td>Retail Price</td><td>${item.costing.currency} ${item.costing.retailPrice.toFixed(2)}</td></tr>`
    : '<tr><td colspan="2">No costing data</td></tr>';

  const html = `<!DOCTYPE html><html><head><title>${item.name} - Spec Sheet</title>
    <style>
      body { font-family: Inter, system-ui, sans-serif; padding: 48px; color: #1E293B; max-width: 800px; margin: 0 auto; }
      h1 { font-size: 28px; margin-bottom: 4px; }
      .meta { color: #64748B; font-size: 14px; margin-bottom: 32px; }
      table { width: 100%; border-collapse: collapse; margin-bottom: 24px; }
      th, td { text-align: left; padding: 10px 16px; border-bottom: 1px solid #E2E8F0; font-size: 14px; }
      th { background: #F8FAFC; font-weight: 600; color: #475569; }
      .badge { display: inline-block; padding: 4px 12px; border-radius: 999px; font-size: 12px; font-weight: 600; background: #EEF2FF; color: #6366F1; }
      .footer { margin-top: 48px; text-align: center; color: #94A3B8; font-size: 12px; }
      @media print { body { padding: 24px; } }
    </style></head><body>
    <h1>${item.name}</h1>
    <p class="meta">${item.sku} · ${item.type} · <span class="badge">${item.status.replace(/-/g, ' ')}</span></p>
    <table><thead><tr><th>Property</th><th>Value</th></tr></thead><tbody>
      <tr><td>Product Type</td><td>${item.type}</td></tr>
      <tr><td>SKU</td><td>${item.sku}</td></tr>
      <tr><td>Status</td><td>${item.status.replace(/-/g, ' ')}</td></tr>
      ${costInfo}
    </tbody></table>
    <p class="footer">Generated by Boxtacks Studio · ${new Date().toLocaleDateString()}</p>
    </body></html>`;

  const win = window.open('', '_blank');
  if (win) {
    win.document.write(html);
    win.document.close();
    setTimeout(() => win.print(), 500);
  }
}

function exportSpecSheet(items: { name: string; sku: string; type: string; status: string; costing?: { unitCost: number; retailPrice: number; currency: string } }[]) {
  const rows = items.map((item) => {
    const cost = item.costing ? `${item.costing.currency} ${item.costing.unitCost.toFixed(2)}` : '-';
    const retail = item.costing ? `${item.costing.currency} ${item.costing.retailPrice.toFixed(2)}` : '-';
    return `<tr><td>${item.name}</td><td>${item.sku}</td><td>${item.type}</td><td>${item.status.replace(/-/g, ' ')}</td><td>${cost}</td><td>${retail}</td></tr>`;
  }).join('');

  const html = `<!DOCTYPE html><html><head><title>Boxtacks - Product Spec Sheet</title>
    <style>
      body { font-family: Inter, system-ui, sans-serif; padding: 48px; color: #1E293B; }
      h1 { font-size: 24px; margin-bottom: 8px; }
      .meta { color: #64748B; font-size: 13px; margin-bottom: 32px; }
      table { width: 100%; border-collapse: collapse; }
      th, td { text-align: left; padding: 8px 12px; border-bottom: 1px solid #E2E8F0; font-size: 13px; }
      th { background: #F8FAFC; font-weight: 600; color: #475569; }
      .footer { margin-top: 48px; text-align: center; color: #94A3B8; font-size: 12px; }
      @media print { body { padding: 24px; } }
    </style></head><body>
    <h1>Product Spec Sheet</h1>
    <p class="meta">${items.length} products · Generated ${new Date().toLocaleDateString()}</p>
    <table><thead><tr><th>Name</th><th>SKU</th><th>Type</th><th>Status</th><th>Unit Cost</th><th>Retail</th></tr></thead>
    <tbody>${rows}</tbody></table>
    <p class="footer">Boxtacks Studio</p>
    </body></html>`;

  const win = window.open('', '_blank');
  if (win) {
    win.document.write(html);
    win.document.close();
    setTimeout(() => win.print(), 500);
  }
}

function isLightHex(hex: string): boolean {
  const c = hex.replace('#', '');
  const r = parseInt(c.substring(0, 2), 16);
  const g = parseInt(c.substring(2, 4), 16);
  const b = parseInt(c.substring(4, 6), 16);
  return (0.299 * r + 0.587 * g + 0.114 * b) / 255 > 0.5;
}

// ─────────────────────────────────────────────────────────────────────────────
// COMPONENT
// ─────────────────────────────────────────────────────────────────────────────
export default function TopNavigation() {
  const {
    activeNavTab, setActiveNavTab,
    setCurrentView, currentView,
    searchQuery, setSearchQuery,
    isDirty, triggerSave,
    openNewCategoryModal, openNewItemModal,
    sidebarExpanded, setSidebarExpanded,
    getActiveItem, setNotification,
    getAllItems, getUnreadCount,
    notifications, markAllNotificationsRead, markNotificationRead, clearNotifications,
  } = useAppStore();

  const [showNewMenu, setShowNewMenu]       = useState(false);
  const [showExportMenu, setShowExportMenu] = useState(false);
  const [showNotifMenu, setShowNotifMenu]   = useState(false);
  const [searchFocused, setSearchFocused]   = useState(false);

  const activeItem = getActiveItem();
  const unreadCount = getUnreadCount();

  const handleNavClick = (tab: typeof NAV_TABS[0]) => {
    setActiveNavTab(tab.id);
    setCurrentView(tab.view);
  };

  const handleExport = (type: string) => {
    const item = activeItem;
    const allItems = getAllItems();

    switch (type) {
      case 'Export PNG':
        if (item) {
          exportAsPNG(item);
          setNotification({ type: 'success', message: `Exported "${item.name}" as PNG` });
        } else {
          setNotification({ type: 'info', message: 'Select a product in Workspace to export PNG' });
        }
        break;
      case 'Export PDF':
        if (item) {
          exportAsPDF(item);
          setNotification({ type: 'success', message: `Opened "${item.name}" spec sheet for printing` });
        } else {
          setNotification({ type: 'info', message: 'Select a product in Workspace to export PDF' });
        }
        break;
      case 'Export Mockup':
        if (item) {
          exportAsPNG(item);
          setNotification({ type: 'success', message: `Exported "${item.name}" mockup as PNG` });
        } else {
          setNotification({ type: 'info', message: 'Select a product in Workspace to export mockup' });
        }
        break;
      case 'Export Spec Sheet':
        if (allItems.length > 0) {
          exportSpecSheet(allItems);
          setNotification({ type: 'success', message: `Opened spec sheet for ${allItems.length} products` });
        } else {
          setNotification({ type: 'info', message: 'No products to export' });
        }
        break;
    }
    setShowExportMenu(false);
  };

  const notifIcon = (type: string) => {
    if (type === 'success') return <CheckCircle size={12} className="text-emerald-500 flex-shrink-0" />;
    if (type === 'error') return <AlertCircle size={12} className="text-red-500 flex-shrink-0" />;
    return <Info size={12} className="text-blue-500 flex-shrink-0" />;
  };

  return (
    <header className="h-14 bg-white border-b border-slate-100 flex items-center px-3 gap-2 z-40 relative shadow-sm flex-shrink-0">

      {/* ── Sidebar toggle + Logo ─────────────────────────────────────────── */}
      <div className="flex items-center gap-2 flex-shrink-0">
        <button
          onClick={() => setSidebarExpanded(!sidebarExpanded)}
          className="w-8 h-8 rounded-lg flex items-center justify-center text-slate-400 hover:text-slate-600 hover:bg-slate-50 transition-colors"
          aria-label="Toggle sidebar"
        >
          {sidebarExpanded ? <X size={16} /> : <Menu size={16} />}
        </button>

        {/* Logo — always navigates home */}
        <button
          onClick={() => { setCurrentView('dashboard'); setActiveNavTab('home'); }}
          className="flex items-center gap-2 group"
        >
          <div className="w-7 h-7 rounded-lg bg-gradient-to-br from-indigo-500 to-purple-600 flex items-center justify-center shadow-sm">
            <span className="text-white font-extrabold text-xs">BT</span>
          </div>
          <span className="font-extrabold text-slate-900 text-sm hidden sm:block tracking-tight">
            Boxtacks
          </span>
        </button>

        {/* Breadcrumb when in workspace */}
        {currentView === 'workspace' && activeItem && (
          <div className="hidden md:flex items-center gap-1.5 text-xs text-slate-400 ml-1 border-l border-slate-100 pl-3">
            <span className="text-[10px] text-slate-400">/</span>
            <span className="font-semibold text-slate-600 truncate max-w-32">{activeItem.name}</span>
          </div>
        )}
      </div>

      {/* ── Nav tabs ─────────────────────────────────────────────────────── */}
      <nav className="hidden lg:flex items-center gap-0.5 flex-1 justify-center">
        {NAV_TABS.map((tab) => {
          const Icon = tab.icon;
          const reallyActive = activeNavTab === tab.id;
          return (
            <button
              key={tab.id}
              onClick={() => handleNavClick(tab)}
              className={`relative flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-semibold transition-all whitespace-nowrap ${
                reallyActive
                  ? 'text-indigo-600 bg-indigo-50'
                  : 'text-slate-500 hover:text-slate-700 hover:bg-slate-50'
              }`}
            >
              <Icon size={13} />
              {tab.label}
              {reallyActive && (
                <motion.div
                  layoutId="navUnderline"
                  className="absolute -bottom-[9px] left-1 right-1 h-0.5 bg-indigo-500 rounded-full"
                  transition={{ type: 'spring', stiffness: 500, damping: 35 }}
                />
              )}
            </button>
          );
        })}
      </nav>

      {/* ── Right controls ───────────────────────────────────────────────── */}
      <div className="flex items-center gap-1.5 flex-shrink-0 ml-auto">

        {/* Search */}
        <div className="relative hidden md:block">
          <Search
            size={13}
            className={`absolute left-3 top-1/2 -translate-y-1/2 transition-colors ${searchFocused ? 'text-indigo-400' : 'text-slate-400'}`}
          />
          <input
            type="text"
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            onFocus={() => setSearchFocused(true)}
            onBlur={() => setSearchFocused(false)}
            placeholder="Search products..."
            className={`pl-8 pr-3 py-1.5 text-xs bg-slate-50 border rounded-xl focus:outline-none text-slate-700 placeholder-slate-400 transition-all ${
              searchFocused
                ? 'w-52 ring-2 ring-indigo-200 border-indigo-300 bg-white'
                : 'w-40 border-slate-200 hover:border-slate-300'
            }`}
          />
        </div>

        {/* Save indicator */}
        <button
          onClick={triggerSave}
          className={`flex items-center gap-1.5 px-3 py-1.5 rounded-xl text-xs font-semibold transition-all ${
            isDirty
              ? 'bg-amber-50 text-amber-600 hover:bg-amber-100 border border-amber-200'
              : 'bg-emerald-50 text-emerald-600 border border-emerald-100'
          }`}
        >
          {isDirty ? <Save size={12} /> : <Check size={12} />}
          <span className="hidden sm:block">{isDirty ? 'Save' : 'Saved'}</span>
        </button>

        {/* Create dropdown */}
        <div className="relative">
          <button
            onClick={() => setShowNewMenu(!showNewMenu)}
            className="flex items-center gap-1.5 px-3 py-1.5 bg-gradient-to-r from-indigo-500 to-purple-600 text-white rounded-xl text-xs font-bold shadow-sm hover:opacity-95 transition-all"
          >
            <Plus size={13} />
            <span className="hidden sm:block">Create</span>
            <ChevronDown size={10} className="hidden sm:block opacity-70" />
          </button>

          <AnimatePresence>
            {showNewMenu && (
              <motion.div
                initial={{ opacity: 0, y: 6, scale: 0.97 }}
                animate={{ opacity: 1, y: 0, scale: 1 }}
                exit={{ opacity: 0, y: 6, scale: 0.97 }}
                transition={{ duration: 0.14 }}
                className="absolute right-0 top-full mt-2 w-52 bg-white border border-slate-100 rounded-2xl shadow-xl z-50 overflow-hidden py-2"
              >
                <div className="px-4 pt-1 pb-2 border-b border-slate-50">
                  <p className="text-[10px] font-semibold text-slate-400 uppercase tracking-wider">Start designing</p>
                </div>
                <button
                  onClick={() => { setCurrentView('dashboard'); setActiveNavTab('home'); setShowNewMenu(false); }}
                  className="w-full text-left px-4 py-2.5 hover:bg-indigo-50 transition-colors flex items-center gap-3"
                >
                  <div className="w-7 h-7 rounded-xl bg-gradient-to-br from-indigo-500 to-purple-600 flex items-center justify-center flex-shrink-0">
                    <Sparkles size={12} className="text-white" />
                  </div>
                  <div>
                    <p className="font-semibold text-xs text-slate-700">New design</p>
                    <p className="text-[10px] text-slate-400">Pick a product type</p>
                  </div>
                </button>
                <button
                  onClick={() => { openNewItemModal(); setShowNewMenu(false); }}
                  className="w-full text-left px-4 py-2.5 hover:bg-indigo-50 transition-colors flex items-center gap-3"
                >
                  <div className="w-7 h-7 rounded-xl bg-purple-100 flex items-center justify-center flex-shrink-0">
                    <Package size={12} className="text-purple-600" />
                  </div>
                  <div>
                    <p className="font-semibold text-xs text-slate-700">Blank product</p>
                    <p className="text-[10px] text-slate-400">Start from scratch</p>
                  </div>
                </button>
                <button
                  onClick={() => { openNewCategoryModal(); setShowNewMenu(false); }}
                  className="w-full text-left px-4 py-2.5 hover:bg-indigo-50 transition-colors flex items-center gap-3"
                >
                  <div className="w-7 h-7 rounded-xl bg-teal-100 flex items-center justify-center flex-shrink-0">
                    <Layers size={12} className="text-teal-600" />
                  </div>
                  <div>
                    <p className="font-semibold text-xs text-slate-700">New category</p>
                    <p className="text-[10px] text-slate-400">Organise your products</p>
                  </div>
                </button>
              </motion.div>
            )}
          </AnimatePresence>
          {showNewMenu && <div className="fixed inset-0 z-40" onClick={() => setShowNewMenu(false)} />}
        </div>

        {/* Export dropdown */}
        <div className="relative">
          <button
            onClick={() => setShowExportMenu(!showExportMenu)}
            className="flex items-center gap-1 px-3 py-1.5 border border-slate-200 text-slate-600 rounded-xl text-xs font-semibold hover:bg-slate-50 hover:border-slate-300 transition-all"
          >
            <Download size={13} />
            <span className="hidden sm:block">Export</span>
          </button>
          <AnimatePresence>
            {showExportMenu && (
              <motion.div
                initial={{ opacity: 0, y: 6, scale: 0.97 }}
                animate={{ opacity: 1, y: 0, scale: 1 }}
                exit={{ opacity: 0, y: 6, scale: 0.97 }}
                className="absolute right-0 top-full mt-2 w-48 bg-white border border-slate-100 rounded-2xl shadow-xl z-50 overflow-hidden py-1"
              >
                {[
                  { label: 'Export PNG', icon: Image, desc: 'Product image' },
                  { label: 'Export PDF', icon: FileText, desc: 'Print-ready spec' },
                  { label: 'Export Mockup', icon: Image, desc: 'Styled product shot' },
                  { label: 'Export Spec Sheet', icon: FileText, desc: 'All products table' },
                ].map(({ label, icon: ItemIcon, desc }) => (
                  <button
                    key={label}
                    onClick={() => handleExport(label)}
                    className="w-full text-left px-4 py-2.5 text-xs text-slate-700 hover:bg-slate-50 transition-colors flex items-center gap-2.5"
                  >
                    <ItemIcon size={12} className="text-slate-400 flex-shrink-0" />
                    <div>
                      <p className="font-medium">{label}</p>
                      <p className="text-[10px] text-slate-400">{desc}</p>
                    </div>
                  </button>
                ))}
              </motion.div>
            )}
          </AnimatePresence>
          {showExportMenu && <div className="fixed inset-0 z-40" onClick={() => setShowExportMenu(false)} />}
        </div>

        {/* Notifications bell with dropdown */}
        <div className="relative">
          <button
            onClick={() => setShowNotifMenu(!showNotifMenu)}
            className="relative w-8 h-8 rounded-xl flex items-center justify-center text-slate-400 hover:text-slate-600 hover:bg-slate-50 transition-colors"
          >
            <Bell size={15} />
            {unreadCount > 0 && (
              <span className="absolute top-1 right-1 w-4 h-4 bg-red-500 text-white text-[9px] font-bold rounded-full flex items-center justify-center">
                {unreadCount > 9 ? '9+' : unreadCount}
              </span>
            )}
          </button>

          <AnimatePresence>
            {showNotifMenu && (
              <motion.div
                initial={{ opacity: 0, y: 6, scale: 0.97 }}
                animate={{ opacity: 1, y: 0, scale: 1 }}
                exit={{ opacity: 0, y: 6, scale: 0.97 }}
                className="absolute right-0 top-full mt-2 w-80 bg-white border border-slate-100 rounded-2xl shadow-xl z-50 overflow-hidden"
              >
                {/* Header */}
                <div className="px-4 py-3 border-b border-slate-50 flex items-center justify-between">
                  <p className="text-xs font-bold text-slate-700">Notifications</p>
                  <div className="flex items-center gap-2">
                    {unreadCount > 0 && (
                      <button
                        onClick={() => markAllNotificationsRead()}
                        className="text-[10px] text-indigo-500 font-semibold hover:text-indigo-700"
                      >
                        Mark all read
                      </button>
                    )}
                    {notifications.length > 0 && (
                      <button
                        onClick={() => clearNotifications()}
                        className="text-slate-400 hover:text-slate-600"
                      >
                        <Trash2 size={11} />
                      </button>
                    )}
                  </div>
                </div>

                {/* List */}
                <div className="max-h-72 overflow-y-auto">
                  {notifications.length === 0 ? (
                    <div className="px-4 py-8 text-center">
                      <Bell size={20} className="mx-auto text-slate-300 mb-2" />
                      <p className="text-xs text-slate-400">No notifications yet</p>
                    </div>
                  ) : (
                    notifications.slice(0, 20).map((n) => (
                      <button
                        key={n.id}
                        onClick={() => markNotificationRead(n.id)}
                        className={`w-full text-left px-4 py-2.5 flex items-start gap-2.5 transition-colors ${
                          n.read ? 'bg-white hover:bg-slate-50' : 'bg-indigo-50/40 hover:bg-indigo-50/60'
                        }`}
                      >
                        <div className="mt-0.5">{notifIcon(n.type)}</div>
                        <div className="flex-1 min-w-0">
                          <p className={`text-xs truncate ${n.read ? 'text-slate-500' : 'text-slate-700 font-medium'}`}>
                            {n.message}
                          </p>
                          <p className="text-[10px] text-slate-400 mt-0.5">
                            {getTimeAgo(n.createdAt)}
                          </p>
                        </div>
                        {!n.read && <span className="w-1.5 h-1.5 rounded-full bg-indigo-500 mt-1.5 flex-shrink-0" />}
                      </button>
                    ))
                  )}
                </div>
              </motion.div>
            )}
          </AnimatePresence>
          {showNotifMenu && <div className="fixed inset-0 z-40" onClick={() => setShowNotifMenu(false)} />}
        </div>

        {/* Avatar */}
        <button className="w-8 h-8 rounded-full bg-gradient-to-br from-indigo-400 to-purple-500 flex items-center justify-center text-white text-xs font-bold hover:opacity-90 transition-opacity shadow-sm">
          A
        </button>
      </div>
    </header>
  );
}

function getTimeAgo(dateStr: string): string {
  const diff = Date.now() - new Date(dateStr).getTime();
  const secs = Math.floor(diff / 1000);
  if (secs < 60) return 'Just now';
  const mins = Math.floor(secs / 60);
  if (mins < 60) return `${mins}m ago`;
  const hours = Math.floor(mins / 60);
  if (hours < 24) return `${hours}h ago`;
  return `${Math.floor(hours / 24)}d ago`;
}
